src/main/java/org/gestorRoles/web/beans/GestorRolesManagedBean.java
package org.gestorRoles.web.beans;

import java.io.Serializable;
import java.util.Collection;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;

import org.richfaces.event.DropEvent;

/**
 *
 * @author david
 */
@ManagedBean(name = "gestorRoles")
@ViewScoped
public class GestorRolesManagedBean implements Serializable{
    
    private String rolSeleccionado;
    
    @ManagedProperty(value = "#{app}")
    private AppManagedBean servicio;

    /**
     * Creates a new instance of GestorRolesManagedBean
     */
    public GestorRolesManagedBean() {
    }

    public String getRolSeleccionado() {
        return rolSeleccionado;
    }

    public void setRolSeleccionado(String rolSeleccionado) {
        this.rolSeleccionado = rolSeleccionado;
    }
    
    public void setServicio(AppManagedBean servicio) {
		this.servicio = servicio;
	}
    
    public Collection<String> getListaRoles(){
        return servicio.getRoles();
    }
    
    public Collection<String> getListaUsuariosEnRol(){
        if(rolSeleccionado != null)
            return servicio.getListaUsuariosEnRol(rolSeleccionado);
        
        return null;
    }
    
    public Collection<String> getListaUsuariosNoEnRol(){
        if(rolSeleccionado != null)
            return servicio.getListaUsuariosNoEnRol(rolSeleccionado);
        
        return null;
    }
    
    public void dragListenerListaUsuariosNoRol(DropEvent ev){
        System.out.println("Drag de rol a usuario");
        String usuario = (String) ev.getDragValue();
        
        servicio.deleteUsuarioDeGrupo(usuario, rolSeleccionado);
    }
    
    public void dragListenerListaUsuariosEnRol(DropEvent ev){
        System.out.println("Drag de usuario a rol");
        String usuario = (String) ev.getDragValue();
        
        servicio.addUsuarioAGrupo(usuario, rolSeleccionado);
    }
}

src/main/webapp/WEB-INF/views/dragdrop.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:a4j="http://richfaces.org/a4j">
	<rich:panel header="Gestión de roles">
		<h:form id="formRol">
            Rol:
            <rich:select value="#{gestorRoles.rolSeleccionado}">
				<f:selectItems value="#{gestorRoles.listaRoles}" />
				<a4j:ajax event="selectitem" execute="@form" render="gestor" />
			</rich:select>
		</h:form>

		<h:panelGroup id="gestor">
			<h:panelGroup rendered="#{gestorRoles.rolSeleccionado != null}">
				<h:form>
					<h:panelGrid columns="2">
						<rich:panel style="width: 300px;height: 650px">
							<rich:dropTarget render="usuariosRol usuariosNoRol" acceptedTypes="usr"
								dropListener="#{gestorRoles.dragListenerListaUsuariosEnRol}" />
							<f:facet name="header">
								<h:outputText value="Usuarios del Rol" />
							</f:facet>
							<h:dataTable id="usuariosRol" value="#{gestorRoles.listaUsuariosEnRol}" var="uR">
								<h:column>
									<a4j:outputPanel layout="block">
										<rich:dragSource dragValue="#{uR}" type="rol" />
										<h:graphicImage width="50" library="img" name="usuario.png" />
										<h:outputText value="#{uR}" />
									</a4j:outputPanel>
								</h:column>
							</h:dataTable>
						</rich:panel>

						<rich:panel style="width: 300px;height: 650px">
							<rich:dropTarget render="usuariosRol usuariosNoRol" acceptedTypes="rol"
								dropListener="#{gestorRoles.dragListenerListaUsuariosNoRol}" />
							<f:facet name="header">
								<h:outputText value="Usuarios del Rol" />
							</f:facet>
							<h:dataTable id="usuariosNoRol" value="#{gestorRoles.listaUsuariosNoEnRol}" var="uNR">
								<h:column>
									<a4j:outputPanel layout="block">
										<rich:dragSource dragValue="#{uNR}" type="usr" />
										<h:graphicImage width="50" library="img" name="usuario.png" />
										<h:outputText value="#{uNR}" />
									</a4j:outputPanel>
								</h:column>
							</h:dataTable>
						</rich:panel>

					</h:panelGrid>
				</h:form>
			</h:panelGroup>
		</h:panelGroup>
	</rich:panel>
</ui:composition>

src/main/webapp/WEB-INF/views/pruebaEmpleado.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich">
	<h:form id="empleado">
		<h:panelGrid columns="3">
            DNI:
            <h:inputText id="dni" value="#{empleadoBean.dni}" required="true">
				<rich:validator />
			</h:inputText>
			<rich:message for="dni" />

            Nombre:
            <h:inputText id="nombre" value="#{empleadoBean.nombre}" required="true">
				<rich:validator />
			</h:inputText>
			<rich:message id="m1" for="nombre" />

            Apellidos:
            <h:inputText id="apellidos" value="#{empleadoBean.apellidos}">
				<rich:validator />
			</h:inputText>
			<rich:message for="apellidos" />

			<h:commandButton value="grabar" action="#{empleadoBean.btnGuardar()}" />
			<a4j:commandButton value="grabar ajax" render="out" action="#{empleadoBean.btnGuardar()}" />
		</h:panelGrid>
            
        out:
        <h:panelGroup id="out">
            DNI:<h:outputText value="#{empleadoBean.dni}" />
            Nombre:<h:outputText value="#{empleadoBean.nombre}" />
            Apellido:<h:outputText value="#{empleadoBean.apellidos}" />
		</h:panelGroup>


		<rich:messages></rich:messages>
	</h:form>
</ui:composition>

src/main/webapp/WEB-INF/views/pruebaValidacionPass.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<f:view xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:a4j="http://richfaces.org/a4j">
    <h:body>
        <h:form>
            <rich:graphValidator value="#{login}">
                <rich:panel header="Cambiar contraseña">
                    <rich:messages/>
                    <h:panelGrid columns="3">
                        Nueva clave:
                        <h:inputSecret value="#{login.password}" id="pass"></h:inputSecret>
                        <rich:message for="pass"/>
                        
                        Repite nueva clave:
                        <h:inputSecret value="#{login.confirm}" id="confirm"></h:inputSecret>
                        <rich:message for="confirm"/>
                    </h:panelGrid>
                    <a4j:commandButton value="Guardar contraseña" action="#{login.almacenarNuevaPassword()}"/>
                </rich:panel>
            </rich:graphValidator>
        </h:form>
    </h:body>
</f:view>

src/main/webapp/WEB-INF/views/view.xhtml
<?xml version="1.0"?>

<f:view
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:rich="http://richfaces.org/rich"
>
	<h:body>
		<rich:panel id="panelId">
			<h:outputText styleClass="bold-hello-world" value="#{i18n['PruebasRichFacesJSF-hello-world']}" />
		</rich:panel>
		<ul>
			<li><em><h:outputText value="#{product.JSF}" /></em></li>
			<li><em><h:outputText value="#{product.LIFERAY_FACES_BRIDGE}" /></em></li>
			<li><em><h:outputText value="#{product.LIFERAY_FACES_BRIDGE_EXT}" /></em></li>
			<li><em><h:outputText value="#{product.LIFERAY_FACES_UTIL}" /></em></li>
			<li><em><h:outputText value="#{product.RICHFACES}" /></em></li>
		</ul>
		<ul>
			<li><h:link outcome="dragdrop" >Prueba dragydrop</h:link></li>
			<li><h:link outcome="empleado" >Prueba bean validation rich</h:link></li>
			<li><h:link outcome="pass" >Prueba bean validation rich password</h:link></li>
		</ul>
	</h:body>
</f:view>